### ISSUE TITLE
Param Tracker

### ISSUE THREAD

**Issue by JGillam** [JGillam/burp-paramalyzer#18]
##Description

This is to replace the deep analysis function to help identify and seek out sensitive information throughout the application.

Basically what I am envisioning is a workflow that goes something like:

1. Perform analysis as usual (over in-scope items)
2. Paramalyzer selects potentially sensitive fields.  You can adjust these.
3. Send sensitive fields to the Param Tracker tab.
4. Build findings from the tracker results (Burp Suite Pro only)

On the Param Tracker tab, some additional analysis will take place.  For parameters with many different values, it will only look for the last (most recent) X values to maintain decent performance.  Two types of analysis will occur as follow:

1. Active Tracking - This is a specialized search.  It will look across all current history (not just in-scope) for additional instances of the parameter value.
2. Passive Tracking - This will continue to track the latest X values for each listed parameter and create findings (for Burp Suite Pro Only)

## Things that will be tracked

- [ ] If the parameter value is a hash, values from all other parameters will be compared to the hash (i.e. they will be hashed with the same algorithm).  This is similar to what Deep Analysis does currently.
- [ ] If the parameter value is encoded, it will be decoded and compared to the decoded values from all other parameters.
- [ ] While being compared to other parameters, it will use a _contains_ check rather than looking for an _exact match_.
- [ ] Response bodies in scope will be checked for the param value. Consider a password being rendered on a page somewhere - generally considered a poor practice.
- [ ] Requests that are not the same origin as where the parameter was found will be checked for the parameter value.  This will include headers, the URL and body; and it will include out-of-scope requests.
- [ ] All URLs (in and out of scope, same and different origins) will be checked for the value.
